### ISSUE TITLE
boost_zlib could not found

### ISSUE THREAD

**Issue by northeastsquare** [mmcs85/eos#6]
Hello, Thank you for great work. When I compile, I met the following problem, boost_zlib could not found. 

 Finished EOS external dependencies installation successfully ---

--- writing CMakeSettings.json ---

Configuring eos

Configuring eos

Configuring eos

-- Using custom FindBoost.cmake
CMake Error at libraries/fc/CMakeModules/FindBoost.cmake:1163 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.66.0

  Boost include path: D:/work/extdeps/boost_1_66_0

  The following Boost libraries could not be found:

          boost_zlib

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  CMakeLists.txt:106 (FIND_PACKAGE)

**Comment by mmcs85** [comment]
Hi, is great to see interest on building EOS for windows without the linux subsystem. 
Related to this issue I have made a fix on the github. Get latest version.

Also since my last tutorial there is a new dependency added for llvm that is python 2.7
Grab it here: https://www.python.org/download/releases/2.7/
